import re
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class EmailAgent:
    """Email Agent that uses an LLM to compose professional emails dynamically."""

    def __init__(self, smtp_server="smtp.gmail.com", smtp_port=587, llm_generate=None):
        """
        :param smtp_server: SMTP server address (default: Gmail)
        :param smtp_port: SMTP port (default: 587 for TLS)
        :param llm_generate: A callable that takes a prompt string and returns generated text.
                             If None, a simple fallback is used (not recommended for production).
        """
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.llm_generate = llm_generate or self._fallback_generate

        # Use environment variables for security (set in .env file)
        self.default_smtp_username = os.getenv('SMTP_USERNAME', '')
        self.default_smtp_password = os.getenv('SMTP_PASSWORD', '')

    def _fallback_generate(self, prompt):
        """Fallback generator when no LLM is provided."""
        return "Subject: Message from AI Assistant\n\nI'm unable to generate a custom email at the moment. Please try again later."

    def _extract_recipient_email(self, user_message):
        """Extract the first valid email address from the user's message."""
        email_match = re.search(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', user_message)
        return email_match.group(0) if email_match else None

    def _generate_email_with_llm(self, user_message):
        """
        Use the LLM to generate a professional email (subject + body) based on the user's request.
        Returns a tuple (subject, body).
        """
        prompt = f"""Based on the following request, write a complete, professional email.
The email must include a subject line starting with 'Subject:' on the first line,
followed by the body. Use a formal salutation, clear structure, and a closing signature.
Do not include any additional commentary.

Request: {user_message}

Email:"""

        generated = self.llm_generate(prompt).strip()

        # Try to extract the subject line (first line starting with "Subject:")
        lines = generated.split('\n', 1)
        subject = "Message from AI Assistant"
        body = generated

        if lines and lines[0].lower().startswith('subject:'):
            subject = lines[0][8:].strip()
            body = lines[1] if len(lines) > 1 else ""

        return subject, body

    def send_email_auto(self, user_message):
        """
        Automatically send an email based on the user's request.
        The email content is generated by the LLM, and the recipient is extracted from the message.
        """
        try:
            # 1. Extract recipient email
            recipient = self._extract_recipient_email(user_message)
            if not recipient:
                return "❌ No recipient email address found. Please include an email address in your request."

            # 2. Check credentials
            if not self.default_smtp_username or not self.default_smtp_password:
                return "❌ SMTP credentials not configured. Please set SMTP_USERNAME and SMTP_PASSWORD environment variables."

            # 3. Generate email content using LLM
            subject, body = self._generate_email_with_llm(user_message)

            # 4. Create the email message
            msg = MIMEMultipart()
            msg['From'] = self.default_smtp_username
            msg['To'] = recipient
            msg['Subject'] = subject
            msg.attach(MIMEText(body, 'plain'))

            # 5. Send via SMTP
            try:
                server = smtplib.SMTP(self.smtp_server, self.smtp_port)
                server.starttls()
                server.login(self.default_smtp_username, self.default_smtp_password)
                server.send_message(msg)
                server.quit()

                return f"✅ **EMAIL SENT SUCCESSFULLY!**\n\n📧 **To:** {recipient}\n📋 **Subject:** {subject}\n\nYour email has been sent."

            except smtplib.SMTPAuthenticationError:
                return "❌ SMTP Authentication Failed. Please check your email credentials (for Gmail, use an App Password if 2FA is enabled)."
            except Exception as e:
                return f"❌ Failed to send email: {str(e)}"

        except Exception as e:
            return f"❌ Error processing email request: {str(e)}"

    def generate_email_preview(self, user_message):
        """
        Generate a preview of the email that would be sent, without actually sending it.
        """
        try:
            recipient = self._extract_recipient_email(user_message)
            if not recipient:
                return "❌ No recipient email address found. Please include an email address."

            subject, body = self._generate_email_with_llm(user_message)

            preview = f"""
📧 **EMAIL PREVIEW**

**To:** {recipient}
**Subject:** {subject}

**Message:**
{body}

---
*Ready to send this email?*
"""
            return preview

        except Exception as e:
            return f"❌ Error generating email preview: {str(e)}"

    def send_email(self, recipient, subject, body, smtp_username=None, smtp_password=None):
        """
        Send an email with explicitly provided credentials (overrides defaults).
        Useful for manual credential input.
        """
        username = smtp_username or self.default_smtp_username
        password = smtp_password or self.default_smtp_password

        if not username or not password:
            return False, "❌ SMTP credentials not provided."

        try:
            msg = MIMEMultipart()
            msg['From'] = username
            msg['To'] = recipient
            msg['Subject'] = subject
            msg.attach(MIMEText(body, 'plain'))

            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(username, password)
            server.send_message(msg)
            server.quit()

            return True, f"✅ Email sent successfully to {recipient}"

        except Exception as e:
            return False, f"❌ Failed to send email: {str(e)}"